#!/usr/bin/env bash
#check if the argument is atleast 1 string
if [ "$1" == "" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
else
	#ping the ip address 5 times
	ping -c 5 "$1"
fi
